name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Backend dependencies and tests
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run backend tests
      working-directory: ./backend
      run: npm test

    # Frontend dependencies and tests
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

    # Build backend Docker image
    - name: Build backend Docker image
      run: docker build -t kanhaiya05/backend:latest ./backend

    # Push backend Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push backend Docker image
      run: docker push kanhaiya05/backend:latest

    # Build frontend Docker image
    - name: Build frontend Docker image
      run: docker build -t kanhaiya05/frontend:latest ./frontend

    # Push frontend Docker image
    - name: Push frontend Docker image
      run: docker push kanhaiya05/frontend:latest
